// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Material_Type int32

const (
	Material_LAMBERT     Material_Type = 0
	Material_BASIC       Material_Type = 1
	Material_PHONG       Material_Type = 2
	Material_STANDARD    Material_Type = 3
	Material_LINE        Material_Type = 4
	Material_DASHED_LINE Material_Type = 5
)

var Material_Type_name = map[int32]string{
	0: "LAMBERT",
	1: "BASIC",
	2: "PHONG",
	3: "STANDARD",
	4: "LINE",
	5: "DASHED_LINE",
}

var Material_Type_value = map[string]int32{
	"LAMBERT":     0,
	"BASIC":       1,
	"PHONG":       2,
	"STANDARD":    3,
	"LINE":        4,
	"DASHED_LINE": 5,
}

func (x Material_Type) String() string {
	return proto.EnumName(Material_Type_name, int32(x))
}

func (Material_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0, 0}
}

type Material_Side int32

const (
	Material_FRONT_SIDE  Material_Side = 0
	Material_BACK_SIDE   Material_Side = 1
	Material_DOUBLE_SIDE Material_Side = 2
)

var Material_Side_name = map[int32]string{
	0: "FRONT_SIDE",
	1: "BACK_SIDE",
	2: "DOUBLE_SIDE",
}

var Material_Side_value = map[string]int32{
	"FRONT_SIDE":  0,
	"BACK_SIDE":   1,
	"DOUBLE_SIDE": 2,
}

func (x Material_Side) String() string {
	return proto.EnumName(Material_Side_name, int32(x))
}

func (Material_Side) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0, 1}
}

type Body_Type int32

const (
	Body_MESH   Body_Type = 0
	Body_BOX    Body_Type = 1
	Body_SPHERE Body_Type = 2
)

var Body_Type_name = map[int32]string{
	0: "MESH",
	1: "BOX",
	2: "SPHERE",
}

var Body_Type_value = map[string]int32{
	"MESH":   0,
	"BOX":    1,
	"SPHERE": 2,
}

func (x Body_Type) String() string {
	return proto.EnumName(Body_Type_name, int32(x))
}

func (Body_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1, 0}
}

type Request_Type int32

const (
	Request_TEXTURE  Request_Type = 0
	Request_AUDIO    Request_Type = 1
	Request_MATERIAL Request_Type = 2
	Request_MESH     Request_Type = 3
)

var Request_Type_name = map[int32]string{
	0: "TEXTURE",
	1: "AUDIO",
	2: "MATERIAL",
	3: "MESH",
}

var Request_Type_value = map[string]int32{
	"TEXTURE":  0,
	"AUDIO":    1,
	"MATERIAL": 2,
	"MESH":     3,
}

func (x Request_Type) String() string {
	return proto.EnumName(Request_Type_name, int32(x))
}

func (Request_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3, 0}
}

type Response_Type int32

const (
	Response_TEXTURE  Response_Type = 0
	Response_AUDIO    Response_Type = 1
	Response_CHUNK    Response_Type = 2
	Response_MATERIAL Response_Type = 3
	Response_MESH     Response_Type = 4
)

var Response_Type_name = map[int32]string{
	0: "TEXTURE",
	1: "AUDIO",
	2: "CHUNK",
	3: "MATERIAL",
	4: "MESH",
}

var Response_Type_value = map[string]int32{
	"TEXTURE":  0,
	"AUDIO":    1,
	"CHUNK":    2,
	"MATERIAL": 3,
	"MESH":     4,
}

func (x Response_Type) String() string {
	return proto.EnumName(Response_Type_name, int32(x))
}

func (Response_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{5, 0}
}

type Light_Type int32

const (
	Light_POINT_LIGHT       Light_Type = 0
	Light_RECT_AREA_LIGHT   Light_Type = 1
	Light_SPOT_LIGHT        Light_Type = 2
	Light_AMBIENT_LIGHT     Light_Type = 3
	Light_DIRECTIONAL_LIGHT Light_Type = 4
	Light_HEMISPHERE_LIGHT  Light_Type = 5
)

var Light_Type_name = map[int32]string{
	0: "POINT_LIGHT",
	1: "RECT_AREA_LIGHT",
	2: "SPOT_LIGHT",
	3: "AMBIENT_LIGHT",
	4: "DIRECTIONAL_LIGHT",
	5: "HEMISPHERE_LIGHT",
}

var Light_Type_value = map[string]int32{
	"POINT_LIGHT":       0,
	"RECT_AREA_LIGHT":   1,
	"SPOT_LIGHT":        2,
	"AMBIENT_LIGHT":     3,
	"DIRECTIONAL_LIGHT": 4,
	"HEMISPHERE_LIGHT":  5,
}

func (x Light_Type) String() string {
	return proto.EnumName(Light_Type_name, int32(x))
}

func (Light_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{6, 0}
}

type Update_Type int32

const (
	Update_LOC Update_Type = 0
)

var Update_Type_name = map[int32]string{
	0: "LOC",
}

var Update_Type_value = map[string]int32{
	"LOC": 0,
}

func (x Update_Type) String() string {
	return proto.EnumName(Update_Type_name, int32(x))
}

func (Update_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{15, 0}
}

type Material struct {
	Color                string        `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	Emissive             string        `protobuf:"bytes,6,opt,name=emissive,proto3" json:"emissive,omitempty"`
	Roughness            float32       `protobuf:"fixed32,7,opt,name=roughness,proto3" json:"roughness,omitempty"`
	Metalness            float32       `protobuf:"fixed32,8,opt,name=metalness,proto3" json:"metalness,omitempty"`
	Scale                float32       `protobuf:"fixed32,9,opt,name=scale,proto3" json:"scale,omitempty"`
	DashSize             float32       `protobuf:"fixed32,11,opt,name=dashSize,proto3" json:"dashSize,omitempty"`
	GapSize              float32       `protobuf:"fixed32,12,opt,name=gapSize,proto3" json:"gapSize,omitempty"`
	TextureID            uint64        `protobuf:"varint,1,opt,name=textureID,proto3" json:"textureID,omitempty"`
	Type                 Material_Type `protobuf:"varint,2,opt,name=type,proto3,enum=pb.Material_Type" json:"type,omitempty"`
	Wireframe            bool          `protobuf:"varint,3,opt,name=wireframe,proto3" json:"wireframe,omitempty"`
	FlatShaded           bool          `protobuf:"varint,10,opt,name=flatShaded,proto3" json:"flatShaded,omitempty"`
	Side                 Material_Side `protobuf:"varint,4,opt,name=side,proto3,enum=pb.Material_Side" json:"side,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Material) Reset()         { *m = Material{} }
func (m *Material) String() string { return proto.CompactTextString(m) }
func (*Material) ProtoMessage()    {}
func (*Material) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *Material) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Material.Unmarshal(m, b)
}
func (m *Material) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Material.Marshal(b, m, deterministic)
}
func (m *Material) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Material.Merge(m, src)
}
func (m *Material) XXX_Size() int {
	return xxx_messageInfo_Material.Size(m)
}
func (m *Material) XXX_DiscardUnknown() {
	xxx_messageInfo_Material.DiscardUnknown(m)
}

var xxx_messageInfo_Material proto.InternalMessageInfo

func (m *Material) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Material) GetEmissive() string {
	if m != nil {
		return m.Emissive
	}
	return ""
}

func (m *Material) GetRoughness() float32 {
	if m != nil {
		return m.Roughness
	}
	return 0
}

func (m *Material) GetMetalness() float32 {
	if m != nil {
		return m.Metalness
	}
	return 0
}

func (m *Material) GetScale() float32 {
	if m != nil {
		return m.Scale
	}
	return 0
}

func (m *Material) GetDashSize() float32 {
	if m != nil {
		return m.DashSize
	}
	return 0
}

func (m *Material) GetGapSize() float32 {
	if m != nil {
		return m.GapSize
	}
	return 0
}

func (m *Material) GetTextureID() uint64 {
	if m != nil {
		return m.TextureID
	}
	return 0
}

func (m *Material) GetType() Material_Type {
	if m != nil {
		return m.Type
	}
	return Material_LAMBERT
}

func (m *Material) GetWireframe() bool {
	if m != nil {
		return m.Wireframe
	}
	return false
}

func (m *Material) GetFlatShaded() bool {
	if m != nil {
		return m.FlatShaded
	}
	return false
}

func (m *Material) GetSide() Material_Side {
	if m != nil {
		return m.Side
	}
	return Material_FRONT_SIDE
}

type Body struct {
	Data                 []float64         `protobuf:"fixed64,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	Material             uint64            `protobuf:"varint,2,opt,name=material,proto3" json:"material,omitempty"`
	Type                 Body_Type         `protobuf:"varint,3,opt,name=type,proto3,enum=pb.Body_Type" json:"type,omitempty"`
	Offset               *RelativeLocation `protobuf:"bytes,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Rotation             *Rotation         `protobuf:"bytes,5,opt,name=rotation,proto3" json:"rotation,omitempty"`
	FlatNormals          bool              `protobuf:"varint,7,opt,name=flatNormals,proto3" json:"flatNormals,omitempty"`
	MeshID               uint64            `protobuf:"varint,8,opt,name=meshID,proto3" json:"meshID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (m *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(m, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetData() []float64 {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Body) GetMaterial() uint64 {
	if m != nil {
		return m.Material
	}
	return 0
}

func (m *Body) GetType() Body_Type {
	if m != nil {
		return m.Type
	}
	return Body_MESH
}

func (m *Body) GetOffset() *RelativeLocation {
	if m != nil {
		return m.Offset
	}
	return nil
}

func (m *Body) GetRotation() *Rotation {
	if m != nil {
		return m.Rotation
	}
	return nil
}

func (m *Body) GetFlatNormals() bool {
	if m != nil {
		return m.FlatNormals
	}
	return false
}

func (m *Body) GetMeshID() uint64 {
	if m != nil {
		return m.MeshID
	}
	return 0
}

type Texture struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Texture) Reset()         { *m = Texture{} }
func (m *Texture) String() string { return proto.CompactTextString(m) }
func (*Texture) ProtoMessage()    {}
func (*Texture) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}

func (m *Texture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Texture.Unmarshal(m, b)
}
func (m *Texture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Texture.Marshal(b, m, deterministic)
}
func (m *Texture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Texture.Merge(m, src)
}
func (m *Texture) XXX_Size() int {
	return xxx_messageInfo_Texture.Size(m)
}
func (m *Texture) XXX_DiscardUnknown() {
	xxx_messageInfo_Texture.DiscardUnknown(m)
}

var xxx_messageInfo_Texture proto.InternalMessageInfo

func (m *Texture) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Request struct {
	Id                   uint64       `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 Request_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Request_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetType() Request_Type {
	if m != nil {
		return m.Type
	}
	return Request_TEXTURE
}

type Mesh struct {
	Vertices             []float64    `protobuf:"fixed64,1,rep,packed,name=vertices,proto3" json:"vertices,omitempty"`
	Faces                []*Mesh_Face `protobuf:"bytes,2,rep,name=faces,proto3" json:"faces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Mesh) Reset()         { *m = Mesh{} }
func (m *Mesh) String() string { return proto.CompactTextString(m) }
func (*Mesh) ProtoMessage()    {}
func (*Mesh) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4}
}

func (m *Mesh) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mesh.Unmarshal(m, b)
}
func (m *Mesh) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mesh.Marshal(b, m, deterministic)
}
func (m *Mesh) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mesh.Merge(m, src)
}
func (m *Mesh) XXX_Size() int {
	return xxx_messageInfo_Mesh.Size(m)
}
func (m *Mesh) XXX_DiscardUnknown() {
	xxx_messageInfo_Mesh.DiscardUnknown(m)
}

var xxx_messageInfo_Mesh proto.InternalMessageInfo

func (m *Mesh) GetVertices() []float64 {
	if m != nil {
		return m.Vertices
	}
	return nil
}

func (m *Mesh) GetFaces() []*Mesh_Face {
	if m != nil {
		return m.Faces
	}
	return nil
}

type Mesh_Face struct {
	A                    uint64    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    uint64    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	C                    uint64    `protobuf:"varint,3,opt,name=c,proto3" json:"c,omitempty"`
	Uvs                  []float64 `protobuf:"fixed64,4,rep,packed,name=uvs,proto3" json:"uvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Mesh_Face) Reset()         { *m = Mesh_Face{} }
func (m *Mesh_Face) String() string { return proto.CompactTextString(m) }
func (*Mesh_Face) ProtoMessage()    {}
func (*Mesh_Face) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4, 0}
}

func (m *Mesh_Face) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mesh_Face.Unmarshal(m, b)
}
func (m *Mesh_Face) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mesh_Face.Marshal(b, m, deterministic)
}
func (m *Mesh_Face) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mesh_Face.Merge(m, src)
}
func (m *Mesh_Face) XXX_Size() int {
	return xxx_messageInfo_Mesh_Face.Size(m)
}
func (m *Mesh_Face) XXX_DiscardUnknown() {
	xxx_messageInfo_Mesh_Face.DiscardUnknown(m)
}

var xxx_messageInfo_Mesh_Face proto.InternalMessageInfo

func (m *Mesh_Face) GetA() uint64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Mesh_Face) GetB() uint64 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *Mesh_Face) GetC() uint64 {
	if m != nil {
		return m.C
	}
	return 0
}

func (m *Mesh_Face) GetUvs() []float64 {
	if m != nil {
		return m.Uvs
	}
	return nil
}

type Response struct {
	Type                 Response_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Response_Type" json:"type,omitempty"`
	Id                   uint64        `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Texture              *Texture      `protobuf:"bytes,3,opt,name=texture,proto3" json:"texture,omitempty"`
	Parts                uint64        `protobuf:"varint,4,opt,name=parts,proto3" json:"parts,omitempty"`
	Part                 uint64        `protobuf:"varint,5,opt,name=part,proto3" json:"part,omitempty"`
	Chunk                *Chunk        `protobuf:"bytes,6,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Material             *Material     `protobuf:"bytes,7,opt,name=material,proto3" json:"material,omitempty"`
	MeshData             []byte        `protobuf:"bytes,8,opt,name=meshData,proto3" json:"meshData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetType() Response_Type {
	if m != nil {
		return m.Type
	}
	return Response_TEXTURE
}

func (m *Response) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetTexture() *Texture {
	if m != nil {
		return m.Texture
	}
	return nil
}

func (m *Response) GetParts() uint64 {
	if m != nil {
		return m.Parts
	}
	return 0
}

func (m *Response) GetPart() uint64 {
	if m != nil {
		return m.Part
	}
	return 0
}

func (m *Response) GetChunk() *Chunk {
	if m != nil {
		return m.Chunk
	}
	return nil
}

func (m *Response) GetMaterial() *Material {
	if m != nil {
		return m.Material
	}
	return nil
}

func (m *Response) GetMeshData() []byte {
	if m != nil {
		return m.MeshData
	}
	return nil
}

type Light struct {
	Type                 Light_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Light_Type" json:"type,omitempty"`
	Color                string            `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Intensity            float32           `protobuf:"fixed32,3,opt,name=intensity,proto3" json:"intensity,omitempty"`
	Position             *RelativeLocation `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             *Rotation         `protobuf:"bytes,5,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Distance             float32           `protobuf:"fixed32,6,opt,name=distance,proto3" json:"distance,omitempty"`
	Decay                float32           `protobuf:"fixed32,7,opt,name=decay,proto3" json:"decay,omitempty"`
	Angle                float32           `protobuf:"fixed32,8,opt,name=angle,proto3" json:"angle,omitempty"`
	Penumbra             float32           `protobuf:"fixed32,9,opt,name=penumbra,proto3" json:"penumbra,omitempty"`
	SecondaryColor       string            `protobuf:"bytes,10,opt,name=secondaryColor,proto3" json:"secondaryColor,omitempty"`
	Width                uint32            `protobuf:"varint,11,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32            `protobuf:"varint,12,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Light) Reset()         { *m = Light{} }
func (m *Light) String() string { return proto.CompactTextString(m) }
func (*Light) ProtoMessage()    {}
func (*Light) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{6}
}

func (m *Light) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Light.Unmarshal(m, b)
}
func (m *Light) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Light.Marshal(b, m, deterministic)
}
func (m *Light) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Light.Merge(m, src)
}
func (m *Light) XXX_Size() int {
	return xxx_messageInfo_Light.Size(m)
}
func (m *Light) XXX_DiscardUnknown() {
	xxx_messageInfo_Light.DiscardUnknown(m)
}

var xxx_messageInfo_Light proto.InternalMessageInfo

func (m *Light) GetType() Light_Type {
	if m != nil {
		return m.Type
	}
	return Light_POINT_LIGHT
}

func (m *Light) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Light) GetIntensity() float32 {
	if m != nil {
		return m.Intensity
	}
	return 0
}

func (m *Light) GetPosition() *RelativeLocation {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Light) GetRotation() *Rotation {
	if m != nil {
		return m.Rotation
	}
	return nil
}

func (m *Light) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *Light) GetDecay() float32 {
	if m != nil {
		return m.Decay
	}
	return 0
}

func (m *Light) GetAngle() float32 {
	if m != nil {
		return m.Angle
	}
	return 0
}

func (m *Light) GetPenumbra() float32 {
	if m != nil {
		return m.Penumbra
	}
	return 0
}

func (m *Light) GetSecondaryColor() string {
	if m != nil {
		return m.SecondaryColor
	}
	return ""
}

func (m *Light) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Light) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Entity struct {
	Location             *RelativeLocation `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Id                   uint64            `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Rotation             *Rotation         `protobuf:"bytes,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Velocity             *Velocity         `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	RotationalVelocity   *Velocity         `protobuf:"bytes,5,opt,name=rotationalVelocity,proto3" json:"rotationalVelocity,omitempty"`
	Bodies               []*Body           `protobuf:"bytes,6,rep,name=bodies,proto3" json:"bodies,omitempty"`
	Lights               []*Light          `protobuf:"bytes,7,rep,name=lights,proto3" json:"lights,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{7}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetLocation() *RelativeLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Entity) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Entity) GetRotation() *Rotation {
	if m != nil {
		return m.Rotation
	}
	return nil
}

func (m *Entity) GetVelocity() *Velocity {
	if m != nil {
		return m.Velocity
	}
	return nil
}

func (m *Entity) GetRotationalVelocity() *Velocity {
	if m != nil {
		return m.RotationalVelocity
	}
	return nil
}

func (m *Entity) GetBodies() []*Body {
	if m != nil {
		return m.Bodies
	}
	return nil
}

func (m *Entity) GetLights() []*Light {
	if m != nil {
		return m.Lights
	}
	return nil
}

type Chunk struct {
	Location             *AbsoluteLocation `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Entities             []*Entity         `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{8}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetLocation() *AbsoluteLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Chunk) GetEntities() []*Entity {
	if m != nil {
		return m.Entities
	}
	return nil
}

type EntityID struct {
	Location             *AbsoluteLocation `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Id                   uint64            `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EntityID) Reset()         { *m = EntityID{} }
func (m *EntityID) String() string { return proto.CompactTextString(m) }
func (*EntityID) ProtoMessage()    {}
func (*EntityID) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{9}
}

func (m *EntityID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntityID.Unmarshal(m, b)
}
func (m *EntityID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntityID.Marshal(b, m, deterministic)
}
func (m *EntityID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntityID.Merge(m, src)
}
func (m *EntityID) XXX_Size() int {
	return xxx_messageInfo_EntityID.Size(m)
}
func (m *EntityID) XXX_DiscardUnknown() {
	xxx_messageInfo_EntityID.DiscardUnknown(m)
}

var xxx_messageInfo_EntityID proto.InternalMessageInfo

func (m *EntityID) GetLocation() *AbsoluteLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *EntityID) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RelativeLocation struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float64  `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelativeLocation) Reset()         { *m = RelativeLocation{} }
func (m *RelativeLocation) String() string { return proto.CompactTextString(m) }
func (*RelativeLocation) ProtoMessage()    {}
func (*RelativeLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{10}
}

func (m *RelativeLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelativeLocation.Unmarshal(m, b)
}
func (m *RelativeLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelativeLocation.Marshal(b, m, deterministic)
}
func (m *RelativeLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelativeLocation.Merge(m, src)
}
func (m *RelativeLocation) XXX_Size() int {
	return xxx_messageInfo_RelativeLocation.Size(m)
}
func (m *RelativeLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_RelativeLocation.DiscardUnknown(m)
}

var xxx_messageInfo_RelativeLocation proto.InternalMessageInfo

func (m *RelativeLocation) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *RelativeLocation) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *RelativeLocation) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Rotation struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	W                    float32  `protobuf:"fixed32,4,opt,name=w,proto3" json:"w,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rotation) Reset()         { *m = Rotation{} }
func (m *Rotation) String() string { return proto.CompactTextString(m) }
func (*Rotation) ProtoMessage()    {}
func (*Rotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{11}
}

func (m *Rotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rotation.Unmarshal(m, b)
}
func (m *Rotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rotation.Marshal(b, m, deterministic)
}
func (m *Rotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rotation.Merge(m, src)
}
func (m *Rotation) XXX_Size() int {
	return xxx_messageInfo_Rotation.Size(m)
}
func (m *Rotation) XXX_DiscardUnknown() {
	xxx_messageInfo_Rotation.DiscardUnknown(m)
}

var xxx_messageInfo_Rotation proto.InternalMessageInfo

func (m *Rotation) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Rotation) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Rotation) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *Rotation) GetW() float32 {
	if m != nil {
		return m.W
	}
	return 0
}

type Velocity struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Velocity) Reset()         { *m = Velocity{} }
func (m *Velocity) String() string { return proto.CompactTextString(m) }
func (*Velocity) ProtoMessage()    {}
func (*Velocity) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{12}
}

func (m *Velocity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Velocity.Unmarshal(m, b)
}
func (m *Velocity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Velocity.Marshal(b, m, deterministic)
}
func (m *Velocity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Velocity.Merge(m, src)
}
func (m *Velocity) XXX_Size() int {
	return xxx_messageInfo_Velocity.Size(m)
}
func (m *Velocity) XXX_DiscardUnknown() {
	xxx_messageInfo_Velocity.DiscardUnknown(m)
}

var xxx_messageInfo_Velocity proto.InternalMessageInfo

func (m *Velocity) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Velocity) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Velocity) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type AbsoluteLocation struct {
	X                    int64    `protobuf:"zigzag64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int64    `protobuf:"zigzag64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    int64    `protobuf:"zigzag64,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AbsoluteLocation) Reset()         { *m = AbsoluteLocation{} }
func (m *AbsoluteLocation) String() string { return proto.CompactTextString(m) }
func (*AbsoluteLocation) ProtoMessage()    {}
func (*AbsoluteLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{13}
}

func (m *AbsoluteLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AbsoluteLocation.Unmarshal(m, b)
}
func (m *AbsoluteLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AbsoluteLocation.Marshal(b, m, deterministic)
}
func (m *AbsoluteLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AbsoluteLocation.Merge(m, src)
}
func (m *AbsoluteLocation) XXX_Size() int {
	return xxx_messageInfo_AbsoluteLocation.Size(m)
}
func (m *AbsoluteLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_AbsoluteLocation.DiscardUnknown(m)
}

var xxx_messageInfo_AbsoluteLocation proto.InternalMessageInfo

func (m *AbsoluteLocation) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *AbsoluteLocation) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *AbsoluteLocation) GetZ() int64 {
	if m != nil {
		return m.Z
	}
	return 0
}

type RelativeAbsoluteLocation struct {
	Absolute             *AbsoluteLocation `protobuf:"bytes,1,opt,name=absolute,proto3" json:"absolute,omitempty"`
	Relative             *RelativeLocation `protobuf:"bytes,2,opt,name=relative,proto3" json:"relative,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RelativeAbsoluteLocation) Reset()         { *m = RelativeAbsoluteLocation{} }
func (m *RelativeAbsoluteLocation) String() string { return proto.CompactTextString(m) }
func (*RelativeAbsoluteLocation) ProtoMessage()    {}
func (*RelativeAbsoluteLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{14}
}

func (m *RelativeAbsoluteLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelativeAbsoluteLocation.Unmarshal(m, b)
}
func (m *RelativeAbsoluteLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelativeAbsoluteLocation.Marshal(b, m, deterministic)
}
func (m *RelativeAbsoluteLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelativeAbsoluteLocation.Merge(m, src)
}
func (m *RelativeAbsoluteLocation) XXX_Size() int {
	return xxx_messageInfo_RelativeAbsoluteLocation.Size(m)
}
func (m *RelativeAbsoluteLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_RelativeAbsoluteLocation.DiscardUnknown(m)
}

var xxx_messageInfo_RelativeAbsoluteLocation proto.InternalMessageInfo

func (m *RelativeAbsoluteLocation) GetAbsolute() *AbsoluteLocation {
	if m != nil {
		return m.Absolute
	}
	return nil
}

func (m *RelativeAbsoluteLocation) GetRelative() *RelativeLocation {
	if m != nil {
		return m.Relative
	}
	return nil
}

type Update struct {
	Type                 Update_Type       `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Update_Type" json:"type,omitempty"`
	Entity               *EntityID         `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	Position             *RelativeLocation `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             *Rotation         `protobuf:"bytes,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Velocity             *Velocity         `protobuf:"bytes,5,opt,name=velocity,proto3" json:"velocity,omitempty"`
	RotationalVelocity   *Velocity         `protobuf:"bytes,6,opt,name=rotationalVelocity,proto3" json:"rotationalVelocity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Update) Reset()         { *m = Update{} }
func (m *Update) String() string { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()    {}
func (*Update) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{15}
}

func (m *Update) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Update.Unmarshal(m, b)
}
func (m *Update) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Update.Marshal(b, m, deterministic)
}
func (m *Update) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Update.Merge(m, src)
}
func (m *Update) XXX_Size() int {
	return xxx_messageInfo_Update.Size(m)
}
func (m *Update) XXX_DiscardUnknown() {
	xxx_messageInfo_Update.DiscardUnknown(m)
}

var xxx_messageInfo_Update proto.InternalMessageInfo

func (m *Update) GetType() Update_Type {
	if m != nil {
		return m.Type
	}
	return Update_LOC
}

func (m *Update) GetEntity() *EntityID {
	if m != nil {
		return m.Entity
	}
	return nil
}

func (m *Update) GetPosition() *RelativeLocation {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Update) GetRotation() *Rotation {
	if m != nil {
		return m.Rotation
	}
	return nil
}

func (m *Update) GetVelocity() *Velocity {
	if m != nil {
		return m.Velocity
	}
	return nil
}

func (m *Update) GetRotationalVelocity() *Velocity {
	if m != nil {
		return m.RotationalVelocity
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.Material_Type", Material_Type_name, Material_Type_value)
	proto.RegisterEnum("pb.Material_Side", Material_Side_name, Material_Side_value)
	proto.RegisterEnum("pb.Body_Type", Body_Type_name, Body_Type_value)
	proto.RegisterEnum("pb.Request_Type", Request_Type_name, Request_Type_value)
	proto.RegisterEnum("pb.Response_Type", Response_Type_name, Response_Type_value)
	proto.RegisterEnum("pb.Light_Type", Light_Type_name, Light_Type_value)
	proto.RegisterEnum("pb.Update_Type", Update_Type_name, Update_Type_value)
	proto.RegisterType((*Material)(nil), "pb.Material")
	proto.RegisterType((*Body)(nil), "pb.Body")
	proto.RegisterType((*Texture)(nil), "pb.Texture")
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Mesh)(nil), "pb.Mesh")
	proto.RegisterType((*Mesh_Face)(nil), "pb.Mesh.Face")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterType((*Light)(nil), "pb.Light")
	proto.RegisterType((*Entity)(nil), "pb.Entity")
	proto.RegisterType((*Chunk)(nil), "pb.Chunk")
	proto.RegisterType((*EntityID)(nil), "pb.EntityID")
	proto.RegisterType((*RelativeLocation)(nil), "pb.RelativeLocation")
	proto.RegisterType((*Rotation)(nil), "pb.Rotation")
	proto.RegisterType((*Velocity)(nil), "pb.Velocity")
	proto.RegisterType((*AbsoluteLocation)(nil), "pb.AbsoluteLocation")
	proto.RegisterType((*RelativeAbsoluteLocation)(nil), "pb.RelativeAbsoluteLocation")
	proto.RegisterType((*Update)(nil), "pb.Update")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 1300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0xf5, 0x90, 0x94, 0x44, 0x5d, 0xf9, 0xc1, 0x4c, 0xd3, 0x82, 0x08, 0xd2, 0x56, 0x61, 0x1e,
	0xd0, 0xa2, 0x30, 0x02, 0xb7, 0xe8, 0x2a, 0x1b, 0x4a, 0x62, 0x22, 0x22, 0x7a, 0x18, 0x23, 0xb9,
	0xc8, 0xce, 0x18, 0x89, 0x63, 0x8b, 0xa8, 0x24, 0xaa, 0x24, 0x65, 0x47, 0x46, 0xd1, 0x1f, 0xe8,
	0xae, 0x7f, 0xd0, 0x5d, 0x3f, 0xa2, 0x7f, 0xd5, 0x5d, 0x57, 0xc5, 0x1d, 0x0e, 0x29, 0xc9, 0x79,
	0xd4, 0xc9, 0x4e, 0xe7, 0x9e, 0xb9, 0x33, 0x9c, 0x73, 0xee, 0xbd, 0x23, 0x30, 0x97, 0xe3, 0xe3,
	0x65, 0x1c, 0xa5, 0x11, 0xd5, 0x96, 0x63, 0xe7, 0x5f, 0x1d, 0xcc, 0x1e, 0x4f, 0x45, 0x1c, 0xf2,
	0x19, 0xbd, 0x0f, 0xa5, 0x49, 0x34, 0x8b, 0x62, 0xbb, 0x54, 0x27, 0x8d, 0x2a, 0xcb, 0x00, 0x7d,
	0x00, 0xa6, 0x98, 0x87, 0x49, 0x12, 0x5e, 0x09, 0xbb, 0x2c, 0x89, 0x02, 0xd3, 0x87, 0x50, 0x8d,
	0xa3, 0xd5, 0xe5, 0x74, 0x21, 0x92, 0xc4, 0xae, 0xd4, 0x49, 0x43, 0x63, 0x9b, 0x00, 0xb2, 0x73,
	0x91, 0xf2, 0x99, 0x64, 0xcd, 0x8c, 0x2d, 0x02, 0x78, 0x5a, 0x32, 0xe1, 0x33, 0x61, 0x57, 0x25,
	0x93, 0x01, 0x3c, 0x2d, 0xe0, 0xc9, 0x74, 0x18, 0xde, 0x08, 0xbb, 0x26, 0x89, 0x02, 0x53, 0x1b,
	0x2a, 0x97, 0x7c, 0x29, 0xa9, 0x7d, 0x49, 0xe5, 0x10, 0x4f, 0x4a, 0xc5, 0xdb, 0x74, 0x15, 0x0b,
	0xbf, 0x6d, 0x93, 0x3a, 0x69, 0x18, 0x6c, 0x13, 0xa0, 0x4f, 0xc1, 0x48, 0xd7, 0x4b, 0x61, 0x6b,
	0x75, 0xd2, 0x38, 0x3c, 0xb9, 0x77, 0xbc, 0x1c, 0x1f, 0xe7, 0x77, 0x3e, 0x1e, 0xad, 0x97, 0x82,
	0x49, 0x1a, 0x37, 0xb9, 0x0e, 0x63, 0x71, 0x11, 0xf3, 0xb9, 0xb0, 0xf5, 0x3a, 0x69, 0x98, 0x6c,
	0x13, 0xa0, 0xdf, 0x00, 0x5c, 0xcc, 0x78, 0x3a, 0x9c, 0xf2, 0x40, 0x04, 0x36, 0x48, 0x7a, 0x2b,
	0x82, 0x87, 0x24, 0x61, 0x20, 0x6c, 0xe3, 0x3d, 0x87, 0x0c, 0xc3, 0x40, 0x30, 0x49, 0x3b, 0x0c,
	0x0c, 0x3c, 0x92, 0xd6, 0xa0, 0xd2, 0x75, 0x7b, 0x4d, 0x8f, 0x8d, 0xac, 0x3d, 0x5a, 0x85, 0x52,
	0xd3, 0x1d, 0xfa, 0x2d, 0x8b, 0xe0, 0xcf, 0xd3, 0xce, 0xa0, 0xff, 0xca, 0xd2, 0xe8, 0x3e, 0x98,
	0xc3, 0x91, 0xdb, 0x6f, 0xbb, 0xac, 0x6d, 0xe9, 0xd4, 0x04, 0xa3, 0xeb, 0xf7, 0x3d, 0xcb, 0xa0,
	0x47, 0x50, 0x6b, 0xbb, 0xc3, 0x8e, 0xd7, 0x3e, 0x97, 0x81, 0x92, 0xf3, 0x23, 0x18, 0x78, 0x02,
	0x3d, 0x04, 0x78, 0xc9, 0x06, 0xfd, 0xd1, 0xf9, 0xd0, 0x6f, 0x7b, 0xd6, 0x1e, 0x3d, 0x80, 0x6a,
	0xd3, 0x6d, 0xbd, 0xce, 0x20, 0x91, 0x79, 0x83, 0xb3, 0x66, 0xd7, 0xcb, 0x02, 0x9a, 0xf3, 0x87,
	0x06, 0x46, 0x33, 0x0a, 0xd6, 0x94, 0x82, 0x11, 0xf0, 0x94, 0xdb, 0xa4, 0xae, 0x37, 0x08, 0x93,
	0xbf, 0xd1, 0x88, 0xb9, 0xfa, 0x7e, 0x29, 0x9c, 0xc1, 0x0a, 0x4c, 0x1f, 0x29, 0x41, 0x75, 0x79,
	0xd7, 0x03, 0xbc, 0x2b, 0xee, 0xb3, 0x2d, 0xe6, 0x77, 0x50, 0x8e, 0x2e, 0x2e, 0x12, 0x91, 0x4a,
	0x41, 0x6a, 0x27, 0xf7, 0x71, 0x11, 0x13, 0x33, 0x9e, 0x86, 0x57, 0xa2, 0x1b, 0x4d, 0x78, 0x1a,
	0x46, 0x0b, 0xa6, 0xd6, 0xd0, 0x06, 0x98, 0x71, 0x94, 0xca, 0x98, 0x2c, 0xbe, 0xda, 0xc9, 0xbe,
	0x5c, 0xaf, 0x62, 0xac, 0x60, 0x69, 0x1d, 0x6a, 0x28, 0x7a, 0x3f, 0x8a, 0xe7, 0x7c, 0x96, 0xd5,
	0x9c, 0xc9, 0xb6, 0x43, 0xf4, 0x2b, 0x28, 0xcf, 0x45, 0x32, 0xf5, 0xdb, 0xb2, 0xe4, 0x0c, 0xa6,
	0x90, 0xf3, 0x54, 0x29, 0x6f, 0x82, 0xd1, 0xf3, 0x86, 0x1d, 0x6b, 0x8f, 0x56, 0x40, 0x6f, 0x0e,
	0xde, 0x58, 0x84, 0x02, 0x94, 0x87, 0xa7, 0x1d, 0x8f, 0xa1, 0x28, 0x5f, 0x43, 0x65, 0x94, 0x55,
	0xce, 0x96, 0x2c, 0xa4, 0xb1, 0x9f, 0xc9, 0xe2, 0x5c, 0x43, 0x85, 0x89, 0x5f, 0x56, 0x22, 0x49,
	0xe9, 0x21, 0x68, 0x61, 0xa0, 0xb4, 0xd1, 0xc2, 0x80, 0x3e, 0x51, 0xaa, 0x10, 0xa9, 0x8a, 0x95,
	0x5d, 0x58, 0x2e, 0xdd, 0x12, 0x06, 0xcd, 0xca, 0x0b, 0x60, 0xe4, 0xbd, 0x19, 0x9d, 0x31, 0x2f,
	0x2b, 0x00, 0xf7, 0xac, 0xed, 0x0f, 0x2c, 0x82, 0xae, 0xf7, 0xdc, 0x91, 0xc7, 0x7c, 0xb7, 0x6b,
	0x69, 0xc5, 0xc7, 0xea, 0xce, 0xef, 0x04, 0x8c, 0x9e, 0x48, 0xa6, 0x68, 0xcc, 0x95, 0x88, 0xd3,
	0x70, 0x22, 0x12, 0x65, 0x58, 0x81, 0xe9, 0x63, 0x28, 0x5d, 0x70, 0x24, 0xb4, 0xba, 0xde, 0xa8,
	0x65, 0xce, 0x60, 0xd2, 0xf1, 0x4b, 0x3e, 0x11, 0x2c, 0xe3, 0x1e, 0x34, 0xc1, 0x40, 0x48, 0xf7,
	0x81, 0x70, 0xd5, 0x2c, 0x84, 0x23, 0x1a, 0xab, 0xcb, 0x90, 0x31, 0xa2, 0x89, 0xb4, 0xd7, 0x60,
	0x64, 0x42, 0x2d, 0xd0, 0x57, 0x57, 0x89, 0x6d, 0xc8, 0xd3, 0xf0, 0xa7, 0xf3, 0xb7, 0x06, 0x26,
	0x13, 0xc9, 0x32, 0x5a, 0x24, 0xa2, 0xe8, 0x2f, 0xb2, 0x29, 0xfd, 0x9c, 0xdb, 0x2e, 0x89, 0xdb,
	0x7a, 0x3d, 0x85, 0x8a, 0xea, 0x51, 0x79, 0x52, 0xed, 0xa4, 0x86, 0x99, 0x4a, 0x7c, 0x96, 0x73,
	0x38, 0x27, 0x96, 0x3c, 0x4e, 0x13, 0x59, 0x48, 0x06, 0xcb, 0x00, 0x7a, 0x83, 0x3f, 0x64, 0xb5,
	0x18, 0x4c, 0xfe, 0xa6, 0xdf, 0x42, 0x69, 0x32, 0x5d, 0x2d, 0x7e, 0x96, 0x63, 0xaa, 0x76, 0x52,
	0xc5, 0xed, 0x5a, 0x18, 0x60, 0x59, 0x1c, 0xcb, 0xac, 0xa8, 0xe9, 0xca, 0xa6, 0xcc, 0xf2, 0x3e,
	0xdd, 0xaa, 0x70, 0xac, 0x7e, 0x91, 0x4c, 0xdb, 0x68, 0xbf, 0x29, 0xed, 0x2f, 0xb0, 0xe3, 0xfe,
	0x8f, 0x83, 0x55, 0x28, 0xb5, 0x3a, 0x67, 0xfd, 0xd7, 0x59, 0x0b, 0x17, 0x66, 0xea, 0x85, 0x99,
	0x86, 0xf3, 0x8f, 0x0e, 0xa5, 0x6e, 0x78, 0x39, 0x4d, 0xa9, 0xb3, 0xa3, 0xdd, 0x21, 0x7e, 0x8e,
	0x24, 0xb6, 0x85, 0x2b, 0xe6, 0xb2, 0xb6, 0x3d, 0x97, 0x1f, 0x42, 0x35, 0x5c, 0xa4, 0x62, 0x91,
	0x84, 0xe9, 0x5a, 0x0a, 0xa8, 0xb1, 0x4d, 0x80, 0x3e, 0x07, 0x73, 0x19, 0x25, 0xa1, 0xec, 0xa8,
	0x8f, 0x75, 0x60, 0xb1, 0xea, 0x13, 0x7a, 0x10, 0x67, 0x74, 0x98, 0xa4, 0x7c, 0x31, 0xc9, 0x5e,
	0x04, 0x9c, 0xd1, 0x0a, 0xe3, 0xb7, 0x06, 0x62, 0xc2, 0xd7, 0xea, 0x35, 0xc8, 0x00, 0x46, 0xf9,
	0xe2, 0x72, 0x26, 0xd4, 0x2b, 0x90, 0x01, 0xdc, 0x67, 0x29, 0x16, 0xab, 0xf9, 0x38, 0xe6, 0xea,
	0x11, 0x28, 0x30, 0x7d, 0x06, 0x87, 0x89, 0x98, 0x44, 0x8b, 0x80, 0xc7, 0xeb, 0x96, 0xbc, 0x3c,
	0xc8, 0xcb, 0xdf, 0x8a, 0xe2, 0xce, 0xd7, 0x61, 0x90, 0x4e, 0xe5, 0x63, 0x71, 0xc0, 0x32, 0x80,
	0x33, 0x60, 0x2a, 0x50, 0x46, 0xf9, 0x50, 0x1c, 0x30, 0x85, 0x9c, 0x5f, 0x95, 0x75, 0x47, 0x50,
	0x3b, 0x1d, 0xf8, 0xfd, 0xd1, 0x79, 0xd7, 0x7f, 0xd5, 0xc1, 0x09, 0xfc, 0x05, 0x1c, 0x31, 0xaf,
	0x35, 0x3a, 0x77, 0x99, 0xe7, 0xaa, 0x20, 0xc1, 0x79, 0x3a, 0x3c, 0x1d, 0xe4, 0x8b, 0x34, 0x7a,
	0x0f, 0x0e, 0xdc, 0x5e, 0xd3, 0xf7, 0x8a, 0x3c, 0x9d, 0x7e, 0x09, 0xf7, 0xda, 0x3e, 0x66, 0xfa,
	0x83, 0xbe, 0xdb, 0x55, 0x61, 0x83, 0xde, 0x07, 0xab, 0xe3, 0xf5, 0xfc, 0x6c, 0xa8, 0xa8, 0x68,
	0xc9, 0xf9, 0x53, 0x83, 0xb2, 0xb7, 0x48, 0x95, 0x3d, 0x33, 0x65, 0x81, 0xb4, 0xfe, 0x83, 0xf6,
	0xe4, 0xab, 0xde, 0xe9, 0x9e, 0x6d, 0xbb, 0xf4, 0x8f, 0xda, 0xd5, 0xc0, 0x81, 0x31, 0x8b, 0x26,
	0x58, 0x27, 0xc6, 0x66, 0xe5, 0x4f, 0x2a, 0xc6, 0x0a, 0x96, 0xbe, 0x00, 0x9a, 0x67, 0xf1, 0x59,
	0xce, 0x6f, 0x17, 0x43, 0x91, 0xf3, 0x9e, 0x75, 0xb4, 0x0e, 0xe5, 0x71, 0x14, 0x84, 0x22, 0xb1,
	0xcb, 0x72, 0xfa, 0x98, 0xf9, 0xbb, 0xc0, 0x54, 0x9c, 0x3e, 0x82, 0xf2, 0x0c, 0x7d, 0xc0, 0xb9,
	0xad, 0xe7, 0x1d, 0x2a, 0xcb, 0x9d, 0x29, 0xc2, 0xe1, 0x50, 0x92, 0x2d, 0xfb, 0x21, 0x85, 0xdc,
	0x71, 0x12, 0xcd, 0x56, 0xe9, 0xfb, 0x14, 0x7a, 0x06, 0xa6, 0x40, 0x75, 0xc3, 0x62, 0xfe, 0x01,
	0x66, 0x64, 0x8a, 0xb3, 0x82, 0x73, 0xba, 0x60, 0x66, 0x31, 0xbf, 0xfd, 0x19, 0xa7, 0xdc, 0xf2,
	0xc1, 0x79, 0x01, 0xd6, 0x6d, 0xd7, 0x70, 0x7a, 0xbe, 0x95, 0xdb, 0x11, 0x46, 0xde, 0x22, 0x5a,
	0xcb, 0x04, 0xc2, 0xc8, 0x1a, 0xd1, 0x8d, 0x34, 0x8c, 0x30, 0x72, 0xe3, 0x34, 0xc1, 0xcc, 0x1d,
	0xdb, 0x64, 0x69, 0x3b, 0x59, 0xda, 0x4e, 0x96, 0xc6, 0xc8, 0x0d, 0xa2, 0x6b, 0x69, 0xa5, 0xc6,
	0xc8, 0xb5, 0xf3, 0x03, 0x98, 0x85, 0x07, 0x77, 0xde, 0x03, 0xbf, 0xfb, 0xf6, 0x2d, 0x37, 0xd9,
	0x74, 0x27, 0x9b, 0xee, 0x64, 0x53, 0xcc, 0xfe, 0x0d, 0xec, 0xfc, 0xd6, 0xef, 0xec, 0xf2, 0x1c,
	0x4c, 0xae, 0x62, 0x1f, 0xd7, 0x34, 0x5f, 0x85, 0x19, 0xb1, 0xda, 0x4d, 0x1e, 0xf8, 0xc1, 0x6e,
	0xc8, 0x57, 0x39, 0x7f, 0x69, 0x50, 0x3e, 0x5b, 0x06, 0x3c, 0x15, 0xf4, 0xf1, 0xce, 0x04, 0x3d,
	0xc2, 0xc4, 0x8c, 0xd9, 0x1e, 0xa1, 0x4f, 0xa0, 0x2c, 0xfd, 0x5f, 0xab, 0xfd, 0xf7, 0x37, 0x95,
	0xe1, 0xb7, 0x99, 0xe2, 0x76, 0x86, 0xa6, 0xfe, 0xc9, 0x43, 0xd3, 0xb8, 0x73, 0x17, 0x96, 0x3e,
	0xa3, 0x0b, 0xcb, 0x77, 0xeb, 0x42, 0xe7, 0x48, 0x8d, 0xb8, 0x0a, 0xe8, 0xdd, 0x41, 0xcb, 0xda,
	0x1b, 0x97, 0xe5, 0xbf, 0xfd, 0xef, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xcd, 0x94, 0xa6,
	0xf9, 0x0b, 0x00, 0x00,
}
